### ISSUE TITLE
Collab: Improve UI aesthetic

### ISSUE THREAD

**Issue by abarganier** [abarganier/ColonyCounter#62]

**Comment by icemanf15** [comment]
The user interface could use some work to make it look nicer. This issue is front-end only and we are not looking for any changes to the functionality of the interface; only changes to appearance should be made. This means we are primarily looking at the html files for the controllers (Dashboard, Navigation, Sidebar, Tutorial, and Result). For front end styling we are using [AngularJS Material](https://material.angularjs.org/latest/). Please make use of these UI components. You should be able to avoid CSS almost entirely using [AngularJS Material's layout](https://material.angularjs.org/latest/layout/introduction) system.

Some things you could work on include:
-better looking color theme
-better looking font/text
-improve tutorial page
-improve landing/upload page (Dashboard controller)
-add logo
-[Font Awesome icons](http://fontawesome.io/icons/)

Improving the UI Aesthetic is fairly open ended; if you think of other ways to improve it that are not listed, feel free to do so.
If you are not sure whether or not you should be making a change to something, please ask first.
If you have any other questions you can contact me or @abarganier
